application: mijn-eerste-website
version: 1
runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: main.php

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1